# Generated by Django 5.2.14 on 2026-07-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_contact_number_appointment_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='insurance_details',
            field=models.CharField(blank=True, help_text='Provider & Policy Number', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='medical_history',
            field=models.TextField(blank=True, help_text='Pre-existing conditions or notes', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='priority_level',
            field=models.CharField(choices=[('Routine', 'Routine'), ('Urgent', 'Urgent'), ('Emergency', 'Emergency')], default='Routine', max_length=20),
        ),
    ]
