# Generated by Django 5.2.14 on 2026-07-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_insurance_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='insurance_details',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='medical_history',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_email',
        ),
        migrations.AddField(
            model_name='appointment',
            name='allergies',
            field=models.TextField(blank=True, help_text='Any known allergies or existing medical conditions', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
