# Generated by Django 5.2.14 on 2026-07-03 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_appointment_insurance_details_and_more'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_age',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_gender',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient'),
        ),
    ]
